name: MCAdmin-Toolkit-Connector
main: org.mcadminToolkit.mcadminToolkit
version: 0.1

commands:
  createAuthKey:
    description: Creates auth key and gives you a download code for it
    usage: /<command> <secLvl>
