name: MCAdmin-Toolkit-Connector
main: org.mcadminToolkit.mcadminToolkit
version: 0.0.1

commands:
  createAccount:
    description: Creates account with randomly generated password, that must be changed. There can't be more than one account with the same login
    usage: /<command> <secLvl> <login>
  listAccounts:
    description: Lists created accounts
    usage: /<command>
  removeAccount:
    description: Removes account with given login
    usage: /<command> <login>
  updateAccount:
    description: Updates security level for account with given login
    usage: /<command> <secLvl> <login>
  resetPassword:
    description: Resets password for account with given login
    usage: /<command> <login>